# Generated by Django 5.2.5 on 2025-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioMars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('image_description', models.ImageField(upload_to='image-studio/')),
                ('text_job', models.TextField(blank=True, verbose_name='Шаги (описание)')),
                ('text_job_ru', models.TextField(blank=True, null=True, verbose_name='Шаги (описание)')),
                ('text_job_en', models.TextField(blank=True, null=True, verbose_name='Шаги (описание)')),
                ('image_job', models.ImageField(upload_to='image-studio/')),
                ('text_prototip', models.TextField(blank=True, verbose_name='Прототип (описание)')),
                ('text_prototip_ru', models.TextField(blank=True, null=True, verbose_name='Прототип (описание)')),
                ('text_prototip_en', models.TextField(blank=True, null=True, verbose_name='Прототип (описание)')),
                ('image_prototip', models.ImageField(upload_to='image-studio/')),
                ('text_prototip_end', models.TextField(blank=True, verbose_name='Прототип (итог, описание)')),
                ('text_prototip_end_ru', models.TextField(blank=True, null=True, verbose_name='Прототип (итог, описание)')),
                ('text_prototip_end_en', models.TextField(blank=True, null=True, verbose_name='Прототип (итог, описание)')),
                ('image_prototip_end', models.ImageField(upload_to='image-studio/')),
            ],
            options={
                'verbose_name': 'Проект Studio Mars',
                'verbose_name_plural': 'Проекты Studio Mars',
            },
        ),
    ]
