# Generated by Django 5.2.5 on 2025-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studiomars_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiomars',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='studiomars',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='studiomars',
            name='text_job_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Шаги (описание)'),
        ),
        migrations.AddField(
            model_name='studiomars',
            name='text_prototip_end_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Прототип (итог, описание)'),
        ),
        migrations.AddField(
            model_name='studiomars',
            name='text_prototip_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Прототип (описание)'),
        ),
    ]
