# Generated by Django 5.2.5 on 2025-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studiomars_description_uk_studiomars_name_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiomars',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL'),
        ),
    ]
